// Auto-generated by bump-version.sh, DO NOT EDIT MANUALLY
public let latestSemVerTag: String = "v1.0.1"
public let buildTimeStamp: String = "070612"
public let cliFullVersion: String = "v1.0.1.070612"
